import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import test from 'node:test';
const techDir = new URL('../src/data/technologies/', import.meta.url);
const categoryIds = new Set(['language','ui-library','web-framework','server-framework','runtime','database','storage','deployment','build-tool','orm']);
async function loadTechnologies() { const names = (await readdir(techDir)).filter((name) => name.endsWith('.json')); return Promise.all(names.map(async (name) => JSON.parse(await readFile(new URL(name, techDir), 'utf8')))); }
test('technology records are unique and complete', async () => { const technologies = await loadTechnologies(); const ids = new Set(technologies.map((technology) => technology.id)); assert.equal(ids.size, technologies.length); assert.ok(technologies.length >= 20); for (const technology of technologies) { assert.match(technology.id, /^[a-z0-9]+(?:-[a-z0-9]+)*$/); assert.ok(technology.name.trim().length > 0); assert.ok(technology.shortDescription.trim().length > 0); assert.ok(technology.whatItDoes.trim().length > 0); assert.ok(technology.officialUrl.startsWith('https://')); assert.ok(categoryIds.has(technology.category)); assert.ok(technology.whenToUse.length > 0); assert.ok(technology.whenNotToUse.length > 0); } });
test('relations only connect real technologies and never self-reference', async () => { const technologies = await loadTechnologies(); const ids = new Set(technologies.map((technology) => technology.id)); const relations = JSON.parse(await readFile(new URL('../src/data/relations.json', import.meta.url), 'utf8')); for (const relation of relations) { assert.ok(ids.has(relation.source), `unknown source: ${relation.source}`); assert.ok(ids.has(relation.target), `unknown target: ${relation.target}`); assert.notEqual(relation.source, relation.target); assert.ok(relation.note.trim().length > 0); } });
test('Astro and Hono are not incorrectly modeled as competitors', async () => { const relations = JSON.parse(await readFile(new URL('../src/data/relations.json', import.meta.url), 'utf8')); assert.equal(relations.some((relation) => relation.type === 'competes-with' && [relation.source, relation.target].includes('astro') && [relation.source, relation.target].includes('hono')), false); });
